### ISSUE TITLE
Fix map scooter icon bugs when API refreshes

### ISSUE THREAD

**Issue by DeeTheDev** [lithictech/suma#172]
Currently in the `mapBuilder.js` file we have scooter markers that are fetched every x amount of seconds with method `startRefreshTimer()`.

The map scooter markers are updated in two ways:
1. When map is moved past it's bounds.
2. Every x amount of seconds (initially or after map is moved)

**Problem:** When we open (spiderfy) a cluster with same location markers (image below), the cluster will close when:
1. map zooms or any markers are added/removed from the group

Our expected behavior is for the spiderfied cluster to stay open when selected/clicked.
We would have to modify leaflet's internal code to accomplish that but this will cause too many refactors.

One solution could be just to allow current behavior and change the cluster and marker color while rising above all other markers/cluster to demonstrate that there is a selected vehicle.

**Clustered/Spiderified vehicles example**
![image](https://user-images.githubusercontent.com/66847768/179878045-64f7fb6b-708a-42f7-859e-63fbc420c05f.png)

**Comment by rgalanakis** [comment]
- Figure out a way to 'tie' a marker to a scooter. We can make an ID based on something like `${o.p}-${o.c[0]}-${o.c[1]}`
- When scooters are requested
- Generate IDs for all new scooters
- Remove markers that are not present in the new list of ids
- Move markers that are present
- Add markers for ids that are missing
- Close the transaction card if the marker for a scooter is now gone (not sure the best way to do this)

**Comment by rgalanakis** [comment]
See if we can solve this by applying a small offset for scooters too close together when we return results.

**Comment by rgalanakis** [comment]
In the endpoint:

```rb
      map_obj.values.each do |vehicles|
        vehicles.group_by { |v| v[:c] }.each do |_, shared_loc_vehicles|
          # Divide 360 by len(shared vehicles) to get the offset of each point around the circle.
          # alpha = Convert degrees to radians
          # d = an offset distance of 0.001 or whatever we find works.
          # offset_lng = lng + (d * cos(alpha))
          # offset_lat = lat + (d * sin(alpha))
          # Set vehicle[:] to {lat: offset_lat, lng: offset_lng}, and use it on the frontend
        end
      end
```
