### ISSUE TITLE
Add discount amount to product page and checkout

### ISSUE THREAD

**Issue by rgalanakis** [lithictech/suma#284]
Instead of just "From Sheridan's Market" it should be "from Sheridan's Market with a 50% discount"

**Comment by rgalanakis** [comment]
@DeeTheDev can you take a stab at this?

- Return a discount percentage on the `OfferingProductEntity` (float between 0 and 1)
- Add a localization string to render the vendor name and discount percentage dynamically (for example, "50% discount" and "discount of 50%" may be needed depending on the language, so the entire "from {vendor name} with {discount_percentage)% discount" should be localized.

**Comment by DeeTheDev** [comment]
> @DeeTheDev can you take a stab at this?
> 
>     * Return a discount percentage on the `OfferingProductEntity` (float between 0 and 1)
> 
>     * Add a localization string to render the vendor name and discount percentage dynamically (for example, "50% discount" and "discount of 50%" may be needed depending on the language, so the entire "from {vendor name} with {discount_percentage)% discount" should be localized.

Yes, I'll take a stab at it.
