### ISSUE TITLE
Overhaul dashboard

### ISSUE THREAD

**Issue by DeeTheDev** [lithictech/suma#432]
A member is usually sent to dashboard after login. We need to forward a validated New Columbia member straight to the food page after login in.

**Comment by rgalanakis** [comment]
I'm wondering if this is better handled by redoing the dashboard so it prompts for relevant information, like available offers and mobility.

**Comment by rgalanakis** [comment]
- Update `Member::Dashboard` and entity to:
  - Include the ids and names of available offerings (`available_offerings: [{id: 1, name: 'abc'}, ...]`
  - Include whether any vehicles are available (`mobility_vehicles_available: true`)
  - (I can help optimize these lookups once they're written and tests are passing)
- Update the dashboard page with offering prompts
  - If the number of offerings available is 0, don't show anything
  - If it's > 1, say "Check out what's available for purchase ->". Link should go to /food
  - If it's == 1, say "Check out what's available for purchase ->." Link should go to the /food/<id> page.
- Update the dashboard page with mobility prompts
  - If there are no vehicles available, don't show anything
  - If there are, show "Get rolling with discounted e-scooters and e-bikes ->". Link should go to /mobility.
