### ISSUE TITLE
Replace 'swipe to claim' with 'press and hold to claim'

### ISSUE THREAD

**Issue by rgalanakis** [lithictech/suma#458]
Swipe isn't working reliably. Let's try a 'press and hold' widget.

**Comment by DeeTheDev** [comment]
We used Bootstrap's [Grow Spinner component](https://react-bootstrap.github.io/docs/components/spinners/#animations) to show a loader when button is pressed.
This solution allows for better understanding that there is a wait time before confirming an orders fulfillment.
