### ISSUE TITLE
Add Oregon to onboarding states

### ISSUE THREAD

**Issue by rgalanakis** [lithictech/suma#508]

**Comment by DeeTheDev** [comment]
I created all 50 states `SupportedGeographies` in production site. We don't necessarily need this change in Bootstrap. This ticket is done:

### Onboarding page supported geographies
![Screenshot 2023-09-15 at 4 33 21 PM](https://github.com/lithictech/suma/assets/66847768/da2d79ec-d698-4b6a-b35b-3474a6f79d1a)

@rgalanakis Please review and close this ticket. Thanks.
