### ISSUE TITLE
Admin autocomplete should not worry about non-word characters

### ISSUE THREAD

**Issue by DeeTheDev** [lithictech/suma#515]
When typing in the memo autocomplete, using a string like `farmers`, the 'memo search 'endpoint returns strings like `farmer's market`. This result doesn't show in the autocomplete because the autocomplete also does its own internal matching against results, and `farmers` and `farmer's` are not the same.

Figure out how to avoid this direct string matching; either don't do the additional layer of filtering at all (let the backend worry about all filtering), or get around it, like the Material fuzzy search autocomplete plugin does (not sure how, look at source).

Remember that autocomplete is generally used for filtering a list of static items, like states/countries; we're using it more like a generic search input.

**Comment by rgalanakis** [comment]
@DeeTheDev can you explain what we know about this issue please.
