### ISSUE TITLE
Add subscription preferences page and support

### ISSUE THREAD

**Issue by rgalanakis** [lithictech/suma#579]
Show different topics (account notifications (disabled), order confirmation, marketing, customer support (disabled)

Turning it on/off can be done in response to STOP can be done by customer support for now. See #578

**Comment by DeeTheDev** [comment]
@rgalanakis List of expected items to complete:
- Build a new unauthed '/messaging-preferences' route.
- Build an authed '/preferences' route, linked from the nav bar.
- They should share the same underlying component, but 'preferences' may have additional components in the future

The component should look like:

---

Subscriptions

[ ] Account Updates
Order updates, receipts, and other messages based on actions you take in suma.

[x] Security
For signing in, and other security-based messages. All suma members receive these messages.

Marketing
Communications from the suma team. You can unsubscribe from these by replying STOP to any marketing message.


---

Endpoints

- From /messaging-preferences route, you want to `GET /v1/messaging/subscriptions` with `authtoken={params.authtoken}`
  - assume 'authtoken' will be a query param on the frontend. if not, you can redirect them to `/`.
  - Response will look like {user: {preferences: {messaging_subscriptions: []}}}
- From /preferences route, assume `user.preferences.messaging_subscriptions` is present (so we don't need another API call)

- The messaging_subscriptions array looks like this:
[
 {key: 'account_updates', checked: true, editable_state: 'on'},
 {key: 'security', checked: true, editable_state: 'off'},
 {key: 'marketing', checked: false, editable_state: 'hidden'},
]

- POST /v1/messaging/subscriptions {account_updates: true}
  - Any unexpected/uneditable keys will be ignored.
  - Response will always be in the shape of a user (a full user if authed, a 'slim' user with just subscription keys if not)

---

After submitting on /preferences, show a success toast or form message. Stay on the same page.
After submitting on /messaging-preferences, show a success view, like you see in 'unsubscribe' links in emails
