### ISSUE TITLE
Improve handling of SMS dispatch failures

### ISSUE THREAD

**Issue by DeeTheDev** [lithictech/suma#603]
When we send SMS and they fail to dispatch, we need a way to capture/log this failure through Sentry or the like.

**Comment by DeeTheDev** [comment]
I think @rgalanakis completed this ticket and is merged to `main`. Lets verify this together.

**Comment by rgalanakis** [comment]
Believe this was fixed in https://github.com/lithictech/suma/commit/82b139ae2868893baab1f1665b060f770ffdd7ee
