### ISSUE TITLE
Avoid creating unnecessary ledgers to members

### ISSUE THREAD

**Issue by DeeTheDev** [lithictech/suma#608]
When visiting `FoodList` page, the API hit will do calculations (from the payment trigger), somewhere in the backend, we are creating new ledgers. Figure out where the issue lies, debug, create a test and fix.

Reproduce:
1. it happens when members load an offering list
2. The API renders pricing calculations and in the process creates multiple ledgers with the ensure_receiving_ledger() trigger method, through noncash_ledger_contrib API private method.
3. This happens during the funding_plan , it ensures that member has the ledger before debiting them with BookTransactions

What we want is to not create those ledgers (or figure a way to not show them in the members ledgers page).
And only create them during the checkout complete process.
Also, this creates multiple ledgers because it takes into account all the triggers.

**Comment by rgalanakis** [comment]
Fixed in https://github.com/lithictech/suma/pull/636
