### ISSUE TITLE
Implement logging for inaccuracies in ledger payments

### ISSUE THREAD

**Issue by DeeTheDev** [lithictech/suma#671]
Figure out ways to do it, document it here

**Comment by rgalanakis** [comment]
What does this mean?

**Comment by DeeTheDev** [comment]
@rgalanakis This is part of our conversation that we had on july 22nd dev meeting. It refers to creating a process to log/notify us if anything in the backend is inaccurate like the book transactions, if a member isn't charged correctly for example or we give more or less subsidy than expected.

**Comment by rgalanakis** [comment]
There is now a chart for it: https://analytics.mysuma.org/question/29-ledgers-with-non-zero-balances
