### ISSUE TITLE
Add `seconds` field for payment triggers in admin

### ISSUE THREAD

**Issue by DeeTheDev** [lithictech/suma#699]
We are setting triggers with `active_during` range and when we save the trigger, we only specify the timestamp hour and minutes. The issue is that timestamps can have seconds when it is submitted, and could lead to having active triggers when they aren't supposed to be active, causing errors like the sentry one below. We must be able to specify seconds or find an better alternative solution.

[Sentry error](https://lithic-technology.sentry.io/issues/5817077340/?environment=production&project=6724127&query=is%3Aresolved&referrer=issue-stream&statsPeriod=90d&stream_index=0)

**Comment by rgalanakis** [comment]
@DeeTheDev can you adjust the other datetimepicker components to use the new one, and ensure the new options work right? (asking for a 'second' works right, etc): https://github.com/lithictech/suma/compare/trunc-time

**Comment by DeeTheDev** [comment]
@rgalanakis Done, I pushed a commit to the branch.
