### ISSUE TITLE
Prevent excessive info logging to Coralogix

### ISSUE THREAD

**Issue by DeeTheDev** [lithictech/suma#721]
We're consistently receiving thousands of info logs in Coralogix everyday around 20:00:00 that causes to exceed the daily limit. Postgres seems to be logging each lime vehicle entry into the database, caused by the `Suma::Async::SyncLimeFreeBikeStatusGbfs` async job.

Check Coralogix dashboard and Slack channel for more details.

**Comment by rgalanakis** [comment]
This was mostly due to turning on 'log all statements' to try to track down the issue/conn issue, but here is a small cleanup: 88df1c7e

@DeeTheDev can you recheck this Friday and make sure we didn't get throttled on Thursday at all?

**Comment by DeeTheDev** [comment]
Thanks for checking on this, I reviewed the changes, looks good. I'll check the logs Friday and update you so we can close this ticket.

**Comment by DeeTheDev** [comment]
@rgalanakis As you can see in the image below, it appears that there's no more excessive logs after the October 22. Similarly, I stopped getting the daily warning emails. 

Looks like it fixed the logging issue and the branch can be deployed to production now.

<img width="533" alt="Screenshot 2024-10-25 at 11 16 08 AM" src="https://github.com/user-attachments/assets/614f77a2-8f2c-4326-a434-a3af45d8d401">
