### ISSUE TITLE
Implement a Program concept and display to actively enrolled members

### ISSUE THREAD

**Issue by DeeTheDev** [lithictech/suma#724]
Manually enroll members to RAMP program (Program Enrollment). We'll have to show the member program information in the dashboard page with subsidy details and description.

### Update dashboard page
Implement a section at the top of the Dashboard page displaying "Programs" that includes an information button. When clicking on this section, members get a popup modal or similar. Then display each program detailing subsidies available for it, that can be applied (and the cash? available)

### Update food checkout page
Test where and how in the checkout it can look better to show Program/Ramp Funds information specifically for Hacienda members. Example:
> You're using subsidy from the 2024 Portland FM to pay this (covered by Portland subsidy and ramp money)

**Comment by rgalanakis** [comment]
Fixed in https://github.com/lithictech/suma/pull/726
