### ISSUE TITLE
Fix undefined values in the frontend

### ISSUE THREAD

**Issue by DeeTheDev** [lithictech/suma#751]
Somewhere in the `FoodPrice`, it is returning [this sentry error](https://lithic-technology.sentry.io/issues/6079141649/?project=6724127&query=is%3Aunresolved%20issue.priority%3Ahigh&referrer=issue-stream&statsPeriod=30d&stream_index=13). Basically, we are possibly passing in an empty Money price somehow.

---

In the `mapBuilder` there is an [undefined element error](https://lithic-technology.sentry.io/issues/5605532129/?project=6724127&query=is%3Aunresolved%20issue.priority%3Ahigh&referrer=issue-stream&statsPeriod=30d&stream_index=9). Debug and fix.

**Comment by rgalanakis** [comment]
We're not worrying about the FoodPrice one for now, the mapBuilder is fixed in #753
